---
- name: "systemctl daemon-reload"
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "systemctl reload alloy"
  ansible.builtin.systemd_service:
    name: "alloy"
    state: reloaded

- name: "systemctl restart alloy"
  ansible.builtin.systemd_service:
    name: "alloy"
    state: restarted
