---
- name: "systemctl daemon-reload"
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "systemctl restart mimir"
  ansible.builtin.systemd_service:
    name: "mimir"
    state: restarted
