---
- name: Prepare
  hosts: instance
  become: true
  tasks:
    - name: "Install python3-debian for deb822_repository module"
      ansible.builtin.apt:
        name: python3-debian
        update_cache: true