---
- name: "systemctl daemon-reload"
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "systemctl restart loki"
  ansible.builtin.systemd_service:
    name: "loki"
    state: restarted
